export const Routes = {
    Splash:'Splash',
    SignUp:'SignUp',
    SignIn: 'SignIn',
    Gender:'Gender',
    Age:'Age',
    Height:'Height',
    Weight:'Weight',
    Goal:'Goal',
    Home:'Home',
    Workout:'Workout',
    Analytics:'Analytics',
    Nutrients:'Nutrients',
    Profile:'Profile',
    Tabs:'Tabs',
    WorkoutStart:'WorkoutStart',
    WorkoutPrompt:'WorkoutPrompt',
    WorkoutPage:'WorkoutPage',
    NutrientsSuggestion:'NutrientsSuggestion',
    NutrientsPlan:'NutrientsPlan',
    Breakfast:'Breakfast',
    Lunch:'Lunch',
    Snacks:'Snacks',
    Dinner:'Dinner',
    WorkoutVideo:'WorkoutVideo',
    FoodPreference:'FoodPreference'
}