export const Diet = [
  {
    name: 'Scrambled Eggs',
    type: 'breakfast',
    vegetarian: false,
    calories: 300,
    protein: 20,
    carbs: 5,
    fat: 22,
    image: require('images/Scrabled_eggs.png'),
  },
  {
    name: 'Oatmeal',
    type: 'breakfast',
    vegetarian: true,
    calories: 250,
    protein: 5,
    carbs: 50,
    fat: 2,
    image: require('images/Oatmeals.png'),

  },
  {
    name: 'Grilled Chicken Salad',
    type: 'lunch',
    vegetarian: false,
    calories: 350,
    protein: 30,
    carbs: 15,
    fat: 18,
    image: require('images/GrilledChickenSalad.png'),

  },
  {
    name: 'Vegetable Stir-Fry',
    type: 'lunch',
    vegetarian: true,
    calories: 300,
    protein: 10,
    carbs: 40,
    fat: 12,
    image: require('images/Vegetable-Stir-Fry.png'),
  },
  {
    name: 'Chicken Biryani',
    type: 'dinner',
    vegetarian: false,
    calories: 500,
    protein: 25,
    carbs: 60,
    fat: 20,
    image: require('images/chicken-Biryani.png'),
  },
  {
    name: 'Paneer Tikka',
    type: 'dinner',
    vegetarian: true,
    calories: 400,
    protein: 18,
    carbs: 15,
    fat: 25,
    image: require('images/paneer_tikka.png'),
  },
  {
    name: 'Spinach and Chickpea Curry',
    type: 'dinner',
    vegetarian: true,
    calories: 350,
    protein: 15,
    carbs: 45,
    fat: 12,
    image: require('images/Spinach-and-Chickpea-Curry.png'),
  },
  {
    name: 'Salmon with Asparagus',
    type: 'dinner',
    vegetarian: false,
    calories: 450,
    protein: 35,
    carbs: 10,
    fat: 28,
    image: require('images/Salmon_with_Asparagus.png'),
  },
  {
    name: 'Greek Yogurt Parfait',
    type: 'snack',
    vegetarian: true,
    calories: 200,
    protein: 12,
    carbs: 30,
    fat: 5,
    image: require('images/Greek_Yogurt_Parfait.png'),
  },
  {
    name: 'Almonds',
    type: 'snack',
    vegetarian: true,
    calories: 150,
    protein: 6,
    carbs: 4,
    fat: 13,
    image: require('images/Almonds.png'),
  },
  {
    name: 'Avocado Toast',
    type: 'breakfast',
    vegetarian: true,
    calories: 350,
    protein: 7,
    carbs: 30,
    fat: 25,
    image: require('images/avocado-toast.png'),
  },
  {
    name: 'Turkey Sandwich',
    type: 'lunch',
    vegetarian: false,
    calories: 400,
    protein: 20,
    carbs: 45,
    fat: 15,
    image: require('images/Turkey_Sandwich.png'),
  },
  {
    name: 'Quinoa Salad',
    type: 'lunch',
    vegetarian: true,
    calories: 300,
    protein: 10,
    carbs: 45,
    fat: 8,
    image: require('images/Quinoa_Salad.png'),
  },
  {
    name: 'Beef Stir-Fry',
    type: 'dinner',
    vegetarian: false,
    calories: 450,
    protein: 30,
    carbs: 20,
    fat: 22,
    image: require('images/Beef-Stir-Fry.png'),

  },
  {
    name: 'Chickpea Curry',
    type: 'dinner',
    vegetarian: true,
    calories: 350,
    protein: 12,
    carbs: 50,
    fat: 10,
    image: require('images/Chickpea_Curry.png'),

  },
  {
    name: 'Greek Salad',
    type: 'lunch',
    vegetarian: true,
    calories: 250,
    protein: 8,
    carbs: 15,
    fat: 18,
    image: require('images/Greek-Salad.png'),

  },
  {
    name: 'Salmon Sushi Roll',
    type: 'dinner',
    vegetarian: false,
    calories: 350,
    protein: 20,
    carbs: 40,
    fat: 12,
    image: require('images/Salmon-Sushi-Roll.png'),

  },
  {
    name: 'Fruit Salad',
    type: 'snack',
    vegetarian: true,
    calories: 150,
    protein: 2,
    carbs: 40,
    fat: 1,
    image: require('images/Fruit-Salad.png'),

  },
  {
    name: 'Protein Shake',
    type: 'snack',
    vegetarian: true,
    calories: 200,
    protein: 20,
    carbs: 10,
    fat: 5,
    image: require('images/protein-shake.png'),

  },
  {
    name: 'Grilled Portobello Mushrooms',
    type: 'dinner',
    vegetarian: true,
    calories: 120,
    protein: 5,
    carbs: 8,
    fat: 9,
    image: require('images/Grilled_Portobello_Mushrooms.png'),
  },
  {
    name: 'Pancakes',
    type: 'breakfast',
    vegetarian: true,
    calories: 400,
    protein: 8,
    carbs: 60,
    fat: 15,
    image: require('images/Pancakes.png'),
  },
  {
    name: 'Chicken Caesar Salad',
    type: 'lunch',
    vegetarian: false,
    calories: 350,
    protein: 25,
    carbs: 10,
    fat: 22,
    image: require('images/Chicken_Caesar_Salad.png'),

  },
  {
    name: 'Veggie Burger',
    type: 'lunch',
    vegetarian: true,
    calories: 300,
    protein: 15,
    carbs: 35,
    fat: 10,
    image: require('images/Veggie_Burger.png'),

  },
  {
    name: 'Beef Burrito',
    type: 'dinner',
    vegetarian: false,
    calories: 550,
    protein: 28,
    carbs: 60,
    fat: 25,
    image: require('images/Beef_Burrito.png'),

  },
  {
    name: 'Tofu Stir-Fry',
    type: 'dinner',
    vegetarian: true,
    calories: 350,
    protein: 15,
    carbs: 30,
    fat: 18,
    image: require('images/Tofu-Stir-Fry.png'),
  },
  {
    name: 'Yogurt and Berries',
    type: 'snack',
    vegetarian: true,
    calories: 180,
    protein: 8,
    carbs: 30,
    fat: 4,
    image: require('images/Yogurt_and_Berries.png'),
  },
  {
    name: 'Shrimp Scampi',
    type: 'dinner',
    vegetarian: false,
    calories: 400,
    protein: 25,
    carbs: 25,
    fat: 22,
    image: require('images/Shrimp_Scampi.png'),
  },
  {
    name: 'Mixed Nuts',
    type: 'snack',
    vegetarian: true,
    calories: 200,
    protein: 5,
    carbs: 10,
    fat: 15,
    image: require('images/Mixed_Nuts.png'),

  },
  {
    name: 'Miso Soup',
    type: 'snack',
    vegetarian: true,
    calories: 100,
    protein: 4,
    carbs: 10,
    fat: 5,
    image: require('images/Miso_Soup.png'),

  },
  {
    name: 'Pork Tenderloin',
    type: 'dinner',
    vegetarian: false,
    calories: 350,
    protein: 30,
    carbs: 5,
    fat: 25,
    image: require('images/Pork_Tenderloin.png'),

  },
  {
    name: 'French Toast',
    type: 'breakfast',
    vegetarian: true,
    calories: 350,
    protein: 6,
    carbs: 45,
    fat: 16,
    image: require('images/French_Toast.png'),

  },
  {
    name: 'Cobb Salad',
    type: 'lunch',
    vegetarian: false,
    calories: 400,
    protein: 20,
    carbs: 15,
    fat: 30,
    image: require('images/Cobb_Salad.png'),

  },
  {
    name: 'Mushroom Risotto',
    type: 'dinner',
    vegetarian: true,
    calories: 450,
    protein: 8,
    carbs: 60,
    fat: 20,
    image: require('images/Mushroom_Risotto.png'),

  },
  {
    name: 'BBQ Pulled Pork Sandwich',
    type: 'lunch',
    vegetarian: false,
    calories: 550,
    protein: 30,
    carbs: 50,
    fat: 25,
    image: require('images/BBQ_Pulled_Pork_Sandwich.png'),

  },
  {
    name: 'Hummus and Veggie Wrap',
    type: 'lunch',
    vegetarian: true,
    calories: 320,
    protein: 10,
    carbs: 45,
    fat: 12,
    image: require('images/Hummus and Veggie Wrap.png'),

  },
  {
    name: 'Grilled Swordfish',
    type: 'dinner',
    vegetarian: false,
    calories: 400,
    protein: 40,
    carbs: 10,
    fat: 20,
    image: require('images/Grilled_Swordfish.png'),

  },
  {
    name: 'Caprese Salad',
    type: 'lunch',
    vegetarian: true,
    calories: 250,
    protein: 12,
    carbs: 10,
    fat: 18,
    image: require('images/Caprese_Salad.png'),

  },
  {
    name: 'Pita Bread with Hummus',
    type: 'snack',
    vegetarian: true,
    calories: 200,
    protein: 6,
    carbs: 30,
    fat: 8,
    image: require('images/Pita_Bread_with_Hummus.png'),
  },
  {
    name: 'Lentil Soup',
    type: 'snack',
    vegetarian: true,
    calories: 150,
    protein: 9,
    carbs: 20,
    fat: 4,
    image: require('images/Lentil_Soup.png'),
  },
  {
    name: 'Beef Tacos',
    type: 'dinner',
    vegetarian: false,
    calories: 450,
    protein: 25,
    carbs: 40,
    fat: 20,
    image: require('images/Beef_Tacos.png'),
  },
  {
    name: 'Dosa',
    type: 'breakfast',
    vegetarian: true,
    calories: 150,
    protein: 3,
    carbs: 30,
    fat: 2,
    image: require('images/Dosa.png'),
  },
  {
    name: 'Idli',
    type: 'breakfast',
    vegetarian: true,
    calories: 60,
    protein: 2,
    carbs: 12,
    fat: 0,
    image: require('images/Idli.png'),
  },
  {
    name: 'Sambhar',
    type: 'lunch',
    vegetarian: true,
    calories: 80,
    protein: 2,
    carbs: 18,
    fat: 1,
    image: require('images/Sambhar.png'),
  },
  {
    name: 'Chicken Chettinad',
    type: 'dinner',
    vegetarian: false,
    calories: 350,
    protein: 20,
    carbs: 15,
    fat: 25,
    image: require('images/Chicken_Chettinad.png'),
  },
  {
    name: 'Rasam',
    type: 'lunch',
    vegetarian: true,
    calories: 50,
    protein: 1,
    carbs: 10,
    fat: 1,
    image: require('images/rasam.png'),
  },
  {
    name: 'Pongal',
    type: 'breakfast',
    vegetarian: true,
    calories: 250,
    protein: 5,
    carbs: 50,
    fat: 2,
    image: require('images/pongal.png'),
  },
  {
    name: 'Fish Curry',
    type: 'dinner',
    vegetarian: false,
    calories: 300,
    protein: 15,
    carbs: 10,
    fat: 20,
    image: require('images/Fish_Curry.png'),
  },
  {
    name: 'Mutton Biriyani',
    type: 'dinner',
    vegetarian: false,
    calories: 500,
    protein: 30,
    carbs: 60,
    fat: 22,
    image: require('images/Mutton_Biriyani.png'),
  },
  {
    name: 'Coconut Chutney',
    type: 'breakfast',
    vegetarian: true,
    calories: 60,
    protein: 1,
    carbs: 5,
    fat: 4,
    image: require('images/Coconut_Chutney.png'),
  },
  {
    name: 'Masala Dosa',
    type: 'breakfast',
    vegetarian: true,
    calories: 300,
    protein: 5,
    carbs: 45,
    fat: 12,
    image: require('images/Dosa.png'),
  },
  {
    name: 'Vada',
    type: 'breakfast',
    vegetarian: true,
    calories: 120,
    protein: 2,
    carbs: 15,
    fat: 6,
    image: require('images/Vada.png'),
  },
  {
    name: 'Curd Rice',
    type: 'lunch',
    vegetarian: true,
    calories: 250,
    protein: 5,
    carbs: 40,
    fat: 7,
    image: require('images/Curd-Rice.png'),
  },
  {
    name: 'Paniyaram',
    type: 'breakfast',
    vegetarian: true,
    calories: 150,
    protein: 3,
    carbs: 25,
    fat: 4,
    image: require('images/Paniyaram.png'),
  },
  {
    name: 'Avial',
    type: 'lunch',
    vegetarian: true,
    calories: 120,
    protein: 2,
    carbs: 15,
    fat: 5,
    image: require('images/Avial.png'),
  },
  {
    name: 'Meen Kuzhambu',
    type: 'dinner',
    vegetarian: false,
    calories: 300,
    protein: 18,
    carbs: 10,
    fat: 20,
    image: require('images/Meen_Kuzhambu.png'),
  },
  {
    name: 'Kozhikari',
    type: 'lunch',
    vegetarian: false,
    calories: 350,
    protein: 22,
    carbs: 30,
    fat: 15,
    image: require('images/Kozhikari.png'),
  },
  {
    name: 'Thalassery Chicken Biryani',
    type: 'dinner',
    vegetarian: false,
    calories: 550,
    protein: 28,
    carbs: 60,
    fat: 25,
    image: require('images/Thalassery_Chicken_Biryani.png'),
  },
  {
    name: 'Ragi Mudde',
    type: 'lunch',
    vegetarian: true,
    calories: 180,
    protein: 4,
    carbs: 35,
    fat: 2,
    image: require('images/Ragi_Mudde.png'),
  },
  {
    name: 'Elaneer Payasam',
    type: 'dessert',
    vegetarian: true,
    calories: 200,
    protein: 1,
    carbs: 30,
    fat: 8,
    image: require('images/Elaneer_Payasam.png'),
  },
];
